# Generated by Django 2.1.1 on 2018-10-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('local_id', models.IntegerField()),
                ('user', models.CharField(max_length=50)),
                ('task', models.CharField(max_length=100)),
                ('start_time', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=100)),
                ('task_date', models.CharField(max_length=100)),
            ],
        ),
    ]
