# Generated by Django 2.1.1 on 2018-10-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_keeper', '0002_auto_20181007_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecord',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
