# Generated by Django 2.1.1 on 2018-10-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_keeper', '0003_auto_20181007_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecord',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
