# Generated by Django 2.1.2 on 2018-10-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_keeper', '0004_auto_20181007_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
