# Generated by Django 2.1.2 on 2018-10-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_keeper', '0007_auto_20181010_0432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timerecord',
            old_name='task',
            new_name='primary_task',
        ),
        migrations.AddField(
            model_name='timerecord',
            name='sub_task',
            field=models.CharField(default='n/a', max_length=100),
            preserve_default=False,
        ),
    ]
