# Generated by Django 2.1.2 on 2018-10-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_keeper', '0009_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
