# Generated by Django 2.1.2 on 2018-10-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_keeper', '0010_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
