# Generated by Django 2.1.2 on 2018-10-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_keeper', '0012_auto_20181011_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='no_of_transactions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='timerecord',
            name='remarks',
            field=models.TextField(null=True),
        ),
    ]
