# Generated by Django 2.1.1 on 2018-12-11 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_keeper', '0013_auto_20181024_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='primary_task',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='time_keeper.PrimaryTask'),
            preserve_default=False,
        ),
    ]
