# Generated by Django 2.1.1 on 2018-12-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_keeper', '0014_auto_20181211_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='completed',
            field=models.BooleanField(default=True),
        ),
    ]
